services:
  caddy:
    image: caddy
    command: caddy reverse-proxy --from https://upayan-statistics-api.upayan.space/ --to http://backend:3110
  backend:
    image: ghcr.io/upayanmazumder/upayan.space:latest
    build: .
    ports:
     - 3110:3000
    env_file:
      - .env